controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    velocity_rolling_window_size: 10
    position_feedback: true
    
    # === FORCE UNSTAMPED VELOCITY ===
    use_stamped_vel: false
    
    # === JAZZY COMPATIBLE PARAMETERS ===
    steering_joints_names: [front_steer_left_joint, front_steer_right_joint]
    traction_joints_names: [rear_left_joint, rear_right_joint]

    wheelbase: 0.67
    steering_track_width: 0.58
    traction_track_width: 0.58
    
    traction_wheels_radius: 0.155 
    steering_wheels_radius: 0.155

    open_loop: false # if True, uses cmd_vel instead of hardware interface feedback to compute odometry
    enable_odom_tf: false
    odom_only_twist: false
    #pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0] # Need to be set if fusing odom with other localization source
    #twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0] # Need to be set if fusing odom with other localization source
    base_frame_id: base_link
    odom_frame_id: odom
    publish_rate: 50.0

    # Rate Limiting
    traction: # All values should be positive
      # min_velocity: 0.0
      # max_velocity: 10.0
      # min_acceleration: 0.0
      max_acceleration: 5.0
      # min_deceleration: 0.0
      max_deceleration: 8.0
      # min_jerk: 0.0
      # max_jerk: 10.0
    steering:
      min_position: -0.461
      max_position: 0.461
      # min_velocity: 0.0
      max_velocity: 1.0
      # min_acceleration: 0.0
      # max_acceleration: 10.0
